version: "3"

services:
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - client
      - server
      
  server:
    container_name: server
    build:
      context: server
      args:
        - SERVER_PORT=${SERVER_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  client:
    container_name: client
    build:
      context: client
    env_file:
      - .env
    restart: always

  postgres:
    container_name: db
    image: postgres:12.4-alpine
    env_file:
      - .env
    restart: always